name: agrisense_mobile
description: "AgriSense - Smart Farming Solutions for Sub-Saharan Africa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.8
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Charts and Graphs
  fl_chart: ^0.71.0
  
  # Date and Time
  intl: ^0.20.2
  
  # Loading and Progress
  flutter_spinkit: ^5.2.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Animations
  lottie: ^3.3.1
  
  # Utils
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
